### ISSUE TITLE
Difference between wingpio and RPi.GPIO (Problems with DHT11)

### ISSUE THREAD

**Issue by sam5665** [ms-iot/samples#260]
Hello,
I want to use https://github.com/szazo/DHT11_Python and I changed the import form "import RPi.GPIO as GPIO" to  "import _wingpio as GPIO" but it just reports Error 1( Missing Data). What are the difference between RPi.GPIO and wingpio, maybe this helps to locate the error.

**Comment by alanch-ms** [comment]
Hello,

Thanks for the report!  We were able to reproduce the problem you have with the DHT11 sensor.  For some reason, when running on Windows IoT core, we are not reading the full 40 bits of data from sensor.  That's why the DHT11_Python library is reporting Error 1 (Missing Data).  We are working on it and will update you as soon as possible.
