### ISSUE TITLE
of DigitalSignageUAP method reloadContentTimer_Tick does not work.

### ISSUE THREAD

**Issue by ghost** [ms-iot/samples#317]
on line 69 of MainPage.xaml.cs:
"if (time.Hour == 0 && time.Minute == 0) // we want the content reload happens only at 0:00 every day, exact mid-night"
I made changes to config.xml however the contents did not get reloaded at mid-night. Can you please advise me? Thanks so much!

I have tried to change the condition above to "if (time.Hour != 0 && time.Minute != 0)" so it reloads every minute as specified here on line 47: "static readonly TimeSpan reloadContentIntervalDuration = new TimeSpan(0, 1, 0);" but that again does not show any sign of reloading contents from new config.xml file that has been changed and ready.

Thank you again!

**Comment by nicogbg** [comment]
since DispatcherTimer aren't guarantee to fire immediately after interval expires and also because
it started some when seconds within a minute there is no guarantee that time will exactly be 0:00 when reloadContentTimer_Tick will be called. You should allow a time window around midnight in the if statement (and debounce).

**Comment by zhuridartem** [comment]
This issue should be fixed in latest version of the code.
