### ISSUE TITLE
Windows.Devices.Gpio namespace not available IoT Extensions Installed

### ISSUE THREAD

**Issue by JohnGalt1717** [ms-iot/samples#373]
None of the samples will work on 3 different installs of Visual Studio 2015 Update 3 Enterprise fully patched. The samples include the IoT extensions in references and there is no error showing on them but in code the namespace isn't available and it fails to compile saying that GpioController doesn't exist etc.

Updating the nuget packages doesn't make any difference.  Rebuild, clean etc. doesn't matter either.

Either I'm missing something or with the latest tools this is broken.

**Comment by IoTGirl** [comment]
Hi John,
This is usually due to mis-matched tools versions. There are many threads like this one in the Windows IoT MSDN forums for example [https://social.msdn.microsoft.com/Forums/en-US/fe438536-67e0-4771-a462-c64a64f8bfeb/windowsdevicesgpio-not-in-namespace?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/fe438536-67e0-4771-a462-c64a64f8bfeb/windowsdevicesgpio-not-in-namespace?forum=WindowsIoT).  I suggest you follow up in that forum as this question is not related to a specific sample in MS-IOT GITHUB.
Sincerely,
IoTGirl
